# Generated by Django 3.2.6 on 2021-10-05 10:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dept', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Mechanical', 'Mechanical'), ('Civil ', 'Civil '), ('Electrical', 'Electrical'), ('ComputerScience', 'Computer Science'), ('Electronics&Communication', 'Electronics & Communication')], default='Computer Science', max_length=40)),
                ('year', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('FirstYear', 'First Year'), ('SecondYear ', 'Second Year '), ('ThirdYear', 'Third Year'), ('FourthYear', 'Fourth Year')], default='First Year', max_length=40)),
                ('semester', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('FirstSemester', 'First Semester'), ('SecondSemester ', 'Second Semester '), ('ThirdSemester', 'Third Semester'), ('FourthSemester', 'Fourth Semester'), ('FifthSemester', 'Fifth Semester'), ('SixthSemester', 'Sixth Semester'), ('SeventhSemester', 'Seventh Semester'), ('EightthSemester', 'Eightth Semester')], default='First Semester', max_length=40)),
                ('enrollment', models.CharField(blank=True, max_length=70, null=True)),
                ('conactno', models.IntegerField(blank=True, max_length=100, null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('is_cdc', models.BooleanField(default=False, verbose_name='Is cdc')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Is teacher')),
                ('is_student', models.BooleanField(default=False, verbose_name='Is student')),
                ('active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.PositiveIntegerField()),
                ('Treacher', models.PositiveIntegerField()),
                ('studentenrollment', models.CharField(max_length=100)),
                ('studentdept', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Mechanical', 'Mechanical'), ('Civil ', 'Civil '), ('Electrical', 'Electrical'), ('ComputerScience', 'Computer Science'), ('Electronics&Communication', 'Electronics & Communication')], default='Computer Science', max_length=40)),
                ('studentyear', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('FirstYear', 'First Year'), ('SecondYear ', 'Second Year '), ('ThirdYear', 'Third Year'), ('FourthYear', 'Fourth Year')], default='First Year', max_length=40)),
                ('studentsemester', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('FirstSemester', 'First Semester'), ('SecondSemester ', 'Second Semester '), ('ThirdSemester', 'Third Semester'), ('FourthSemester', 'Fourth Semester'), ('FifthSemester', 'Fifth Semester'), ('SixthSemester', 'Sixth Semester'), ('SeventhSemester', 'Seventh Semester'), ('EightthSemester', 'Eightth Semester')], default='First Semester', max_length=40)),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Data Structure & Algorithms', 'Data Structure & Algorithms'), ('Circuit Theory & Networks', 'Circuit Theory & Networks'), ('Computer Organisation', 'Computer Organisation'), ('Digital Electronics & Logic Design', 'Digital Electronics & Logic Design'), ('Principles of Programming Language', 'Principles of Programming Language'), ('Formal Language & Automata Theory', 'Formal Language & Automata Theory'), ('Operation Research & Optimization Techniques', 'Operation Research & Optimization Techniques'), ('Principles of Communication Engg', 'Principles of Communication Engg'), ('Advanced Computer Architecture', 'Advanced Computer Architecture'), ('Operating System', 'Operating System'), ('Database Management System', 'Database Management System'), ('Design & Analysis of Algorithm', 'Design & Analysis of Algorithm'), ('Microprocessor & Microcontrollers', 'Microprocessor & Microcontrollers'), ('Control System', 'Control System'), ('Computer network', 'Computer network'), ('Software Engineering', 'Software Engineering'), ('Computer Graphics & Multimedia', 'Computer Graphics & Multimedia'), ('System Software and Administration', 'System Software and Administration'), ('Object Technology & UML', 'Object Technology & UML'), ('Language \xa0Processor', 'Language \xa0Processor'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Visual Programming and Web technology', 'Visual Programming and Web technology'), ('Financial Management and accounts', 'Financial Management and accounts')], default='Mathematics', max_length=80)),
                ('total_attendence', models.IntegerField(default=0)),
                ('total_class', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('total_makrs', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityname', models.CharField(max_length=70)),
                ('activitydetails', models.TextField(max_length=500)),
                ('activityimage', models.ImageField(blank=True, null=True, upload_to='Activity/')),
                ('activitydate', models.DateField(blank=True, null=True)),
                ('activityowner', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.TextField(max_length=100)),
                ('details', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Pic/')),
                ('dept', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Civil ', 'Civil '), ('Electrical', 'Electrical'), ('ComputerScience', 'Computer Science'), ('Electronics&Communication', 'Electronics & Communication'), ('placement', 'Placement'), ('admission', 'Admission'), ('event', 'Event'), ('CDC', 'CDC')], default='Computer Science', max_length=100)),
                ('owner', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
                ('postedtime', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('questioncategory', models.PositiveIntegerField(null=True)),
                ('questionimage', models.ImageField(blank=True, null=True, upload_to='Question/Pic/')),
                ('questionfile', models.FileField(blank=True, max_length=1000, null=True, upload_to='Question/file/')),
                ('owner', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('postedtime', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('owner', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.ImageField(blank=True, null=True, upload_to='Pin/Pic/')),
                ('heading', models.TextField(max_length=100)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('pincategory', models.CharField(choices=[('Campus', 'Campus'), ('Carrer', 'Carrer'), ('Culture', 'Culture'), ('Sports', 'Sports'), ('Student', 'Student'), ('Teacher', 'Teacher')], default='Campus', max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('postedtime', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=1000)),
                ('solver', models.PositiveIntegerField()),
                ('answertime', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.question')),
            ],
        ),
    ]
