# Generated by Django 3.2.6 on 2021-10-05 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211005_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enddate',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/mern-commerce/image/upload/v1633459954/usericon_hpewnq.png', null=True, upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='startdate',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
