# Generated by Django 3.2.6 on 2021-10-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211006_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='conactno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
