# Generated by Django 3.2.6 on 2021-10-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_conactno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='total_attendence',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='total_class',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='total_makrs',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='conactno',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='startdate',
        ),
        migrations.AddField(
            model_name='academic',
            name='subjectattendence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='academic',
            name='subjectclass',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='academic',
            name='subjectmarks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='academic',
            name='subjectscore',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
