# Generated by Django 3.2.6 on 2021-10-06 01:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211006_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activitydetails',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
