# Generated by Django 3.2.6 on 2021-10-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_activity_activitydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityowner',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
