# Generated by Django 3.2.6 on 2021-10-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_pin_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='Student',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='Treacher',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='subjectattendence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='subjectclass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='subjectmarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='subjectscore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
